### ISSUE TITLE
No support for Mautic 3

### ISSUE THREAD

**Issue by MauriceW2** [virgilwashere/mautic-cron-commands#9]
This version does not seem to work with Mautic 3 yet.

Could you please update this to support Mautic v3?

**Comment by fredroo** [comment]
Follow @virgilwashere return page not found

**Comment by virgilwashere** [comment]
> Follow @virgilwashere return page not found

That seems to work for me.

**Comment by virgilwashere** [comment]
> This version does not seem to work with Mautic 3 yet.
> 
> Could you please update this to support Mautic v3?

I shall 

- [ ] investigate the viability of getting this project to work with Mautic 3

- [ ] update README.md to clearly state versions supported

**Comment by fredroo** [comment]
thanks a lot @virgilwashere

**Comment by fredroo** [comment]
@virgilwashere are some prevision to release update Mautic 3?

**Comment by pagelab** [comment]
@fredroo This is a `.htaccess` issue. You should add your `commands.php` file to the whitelist in the Mautic's `.htaccess` file, line 113, like that:

Before:
````
    # Except those whitelisted bellow.
    <FilesMatch "^(index|index_dev|filemanager|upgrade)\.php$">
        Require all granted
    </FilesMatch>

````

After:
````
    # Except those whitelisted bellow.
    <FilesMatch "^(index|index_dev|filemanager|upgrade|commands)\.php$">
        Require all granted
    </FilesMatch>
````
